---
# Example for an ansible inventory file
all:
  children:
    bootstraps:
      hosts:
        # Public IP Address of the Bootstrap Node
        192.168.100.23:
    masters:
      hosts:
        # Public IP Addresses for the Master Nodes
        192.168.100.11:
    agents:
      hosts:
        # Public IP Addresses for the Agent Nodes
        192.168.100.22:
        192.168.100.21:
        192.168.100.24:
        192.168.100.31:
        192.168.100.32:
    agent_publics:
      hosts:
        # Public IP Addresses for the Public Agent Nodes
        192.168.100.12:
  vars:
    # IaaS target for DC/OS deployment
    # options: aws, gcp, azure or onprem
    dcos_iaas_target: 'onprem'

    # Choose the IP Detect Script
    # options: eth0, eth1, ... (or other device name for existing network interface)
    dcos_ip_detect_interface: 'eno1'

    # (internal/private) IP Address of the Bootstrap Node
    dcos_bootstrap_ip: '192.168.100.23'

    # (internal/private) IP Addresses for the Master Nodes
    dcos_master_list:
      - 192.168.100.11

    # DNS Resolvers
    dcos_resolvers:
      - 192.168.100.101
    
    dcos_dns_search: 'None'

    # Internal Loadbalancer DNS for Masters (only needed for exhibitor: aws_s3)
    dcos_exhibitor_address: 'master01.bigdata.es'

    # External Loadbalancer DNS for Masters or 
    # (external/public) Master Node IP Address (only needed for cli setup) 
    dcos_master_address: 'master01.bigdata.es'


    oauth_enabled: 'false'
    telemetry_enabled: 'false'
    use_proxy: 'true'
    http_proxy: http://10.114.80.6:3128
    https_proxy: https://10.114.80.6:3128
    no_proxy:
      - '.bigdata.es'
      - '.mesos'
      - '.thisdcos.directory'
      - '.dcos.directory'
      - '.zk'
      - '127.0.0.1'
      - 'localhost'
